---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  client_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[mumble::server]
    attributes:
